### ISSUE TITLE
Friendly note on unexpected side-effects of 2.1.5->2.1.6 transition

### ISSUE THREAD

**Issue by ukstv** [achingbrain/uint8arrays#21] opened 2021-07-15 12:12 UTC
Using marvellous `uint8arrays` library extensively. The recent change depends on `multiformats` module instead of previous `multibase`. Apparently, `multiformats` uses [conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports) in its `package.json`, and vanilla Jest can not handle those.

So, if some people start complaining on their tests failing with cryptic errors, like `Cannot read property 'base16' of undefined`, please know, this is due to Jest unable to load `multiformats` properly.

A solution I have for the downstream users is to use custom resolver for Jest ([jest-resolver-enhanced](https://www.npmjs.com/package/jest-resolver-enhanced)), like in the following fragment of `package.json`:
```json
{
  "jest": {
    "resolver": "jest-resolver-enhanced"
  },
}
```

Any other resolver capable of handling conditional exports is just as fine, but every one I know of, are unusable right now due to old age. Checked them all, IMO.

**Comment by achingbrain** [comment] 2021-07-15 13:28
Ah, that's annoying, sorry about that.

I've just opened https://github.com/mikeal/ipjs/pull/14 which when building `multiformats` with the changes in that PR means it works with jest for me locally.  I'll get a `multiformats` release out as soon as it's merged.

In the mean time please use your custom resolver or pin `uint8arrays` to `2.1.5`.

**Comment by achingbrain** [comment] 2021-07-15 16:17
This should be fixed in `multiformats@9.4.2`.  I've published `uint8arrays@2.1.7` which sets this as the minimum version of `multiformats` for the dependency.

Please let me know if this still causes you problems.

**Comment by achingbrain** [comment] 2021-07-16 08:30
Closing this as it should be fixed, please re-open if you continue to see problems.

**Closed by achingbrain** 2021-07-16 08:30 UTC

**Comment by ukstv** [comment] 2021-07-17 11:01
Thanks @achingbrain

**Comment by alexeygorbachevskiy** [comment] 2022-12-12 10:02
@achingbrain It seems the issue is being reproduced for now. I had the error "Cannot read property 'base16' of undefined" and fixed it only via resolver as was suggested above ->
{
  "jest": {
    "resolver": "jest-resolver-enhanced"
  },
}
